### ISSUE TITLE
Pre 0.1.5 existing games won't load

### ISSUE THREAD

**Issue by SLE-TheRealOne** [joranbeasley/Factorio-PeaceAndProsperity#5]
Hi,

First of all, **thanks for this amazing work !!!**

Since 0.1.5 update, i can not load existing saves (that were based on 0.01.0). I identified the issue, made a correction commit and successfully tested it ; both pre-0.1.5 games and new games alike are ok.

Could clone your repo but, unfortunately, can't push a dedicated branch.

How would you proceed ? Can you open write access or do you rather get correction by another media ?

**Comment by joranbeasley** [comment]
Thanks for the feedback @SLE-TheRealOne 

I dont think you can open write access to just one branch 

I created a dev branch, please fork that branch, and make the changes, and submit a pull request back to me :) which I will accept and close this issue with :)

**Comment by SLE-TheRealOne** [comment]
Here is the PR #6 

BTW allowing write access for branches shall be available in github (i am more used to Atlassian Bitbucket). I'll look tomorrow

**Comment by joranbeasley** [comment]
merged in PR :)
